image: ruby:2.3
stages:
    - build
    - deploy

build:
    script:
    - cd ./src
    - bundle install
    - jekyll build
    artifacts:
        paths:
        - ./src/_site
    only:
    - master
    stage: build

deploy:
    script:
        - apt-get update
        - apt-get --yes --force-yes install rsync
        - ls src
        - mkdir "${HOME}/.ssh"
        - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
        - echo "${SSH_PRIVATE_KEY}" > "${HOME}/.ssh/id_rsa"
        - chmod 700 "${HOME}/.ssh/id_rsa"
        - rsync -chrtvzP -e "ssh -i ${HOME}/.ssh/id_rsa" src/_site tdr@104.248.116.88:/home/tdr/vhosts/richartl.info
    artifacts:
        paths:
        - ./src/_site
    only:
    - master
    stage: deploy
