image: ruby:2.3

before_script:
- cd ./src
- bundle install

build:
    script:
    - jekyll build -d public
    - pwd
    - ls
    artifacts:
        paths:
        - ./src/public
    only:
    - master
    stage: build
