# Site setings
name: 'richartl'
description: 'El mejor lugar donde puedes leer acerca de cosas high-tech y de deporte en el mismo lugar. El crossover entre el mundo nerd y los chicos cool que juegan deportes, RARO VERDAD? imaginate! esto es apenas la descripción!'
meta_description: 'El blog del chico devops deportista'
logo: 'assets/images/logos/logo@120px.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://richartl.info/
disqus: 'richartl-info'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bg5.png
# Add your GA Tracking Id
ga_analytics: UA-150991016-1


# Author
author:
  name: 'Ricardo Alberto Pérez Candelas'
  image: 'author1.jpg'
  greetings: "Ricardo Alberto Pérez Candelas"
  description: "Este es el espacio bizarro donde se juntan ... CULTURA DEVOPS, DEPORTES, MAN-LIFESTYLE y porque no!! MUSICA también"
  bio: 'Ricardo es ingeniero en sistemas, desarrollador back-end y un poco front-end, activo en las comunidades acerca de infraestructura, deportista, musico y loco'

# Contact form setings
email: el@richartl.info
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Todo correcto!!, gracias por contactarme, en un rato no muy largo te estaré respondiendo!!"

# Social links
#twitter: 'username'
#facebook: 'username'
github: 'richartl'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
instagram: 'elrichartl'
#pinterest: 'username'
#linkedin: 'username'
#producthunt: '@username'

# Navigation
navigation:
  #- text: About
    #url: /about/
  #- text: Style Guide
    #url: /style-guide/
  #- text: Contact Me
    #url: /contact/

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
